name: 'Generate full install manifests'

on:
  push:
    # TODO(operator-rename): Change this to main at some point so that we update the manifest bundle.
    # This will need to be run post-release.
    branches:
    - alex/single-manifest-file
    # paths:
    # - 'helm/**/*'
  # pull_request_target:
  #   branches:
  #   - main
  #   paths:
  #   - 'helm/**/*'
permissions:
  contents: write
jobs:
  update-full-install:
    name: Update full install
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34
      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@b8276522d77f21bf19d3574e5bc99186a6c7aa6c
      - name: Run helm template
        run: nix develop --command make manifest-bundle
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update full install manifests file
