name: Tests
on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]
  # For testing/iteration on these e2e tests
  # 1. Create a branch and PR in the ngrok/ngrok-operator repo
  # 2. uncomment the block below
  # 3. Push a PR
  # pull_request:
  #   branches: [ "main" ]

env:
  GO_VERSION: '1.23'
  DOCKER_BUILDX_PLATFORMS: linux/amd64,linux/arm64

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      charts: ${{ steps.changes.outputs.charts }}
      chartyaml: ${{ steps.changes.outputs.chartyaml }}
      go: ${{ steps.changes.outputs.go }}
      tag: ${{ steps.changes.outputs.tag }}
      tests: ${{ steps.changes.outputs.tests }}
      make: ${{ steps.changes.outputs.make }}
    steps:
    - uses: actions/checkout@v3
    - uses: "./.github/actions/changes"
      id: changes

  build-and-test-e2e:
    runs-on: ubuntu-latest
    needs:
    - changes
    if: |
      (needs.changes.outputs.go == 'true') ||
      (needs.changes.outputs.charts == 'true') ||
      (needs.changes.outputs.chartyaml == 'true') ||
      (needs.changes.outputs.tests == 'true') ||
      (needs.changes.outputs.make == 'true')
    permissions:
      contents: read
      pull-requests: read
    steps:
    - name: Confirm 'safe to test'
      # PRs from forks must be labeled 'safe to test' to run e2e tests
      # Merges to main are tested automatically
      if: |
        !(github.event_name == 'push' && github.ref_name == 'main')
        &&
        !(contains(github.event.pull_request.labels.*.name, 'safe to test'))
      run: |
        echo 'This PR is not labeled "safe to test", blocking e2e tests...'
        echo "Found labels: ${{ github.event.pull_request.labels }}"
        exit 1 # intentionally fail the job
    # checkout the repo at the PR's head sha (inside the fork's commits)
    # this allows forks to test changes to the go code and e2e tests
    - uses: actions/checkout@v3
<<<<<<< Updated upstream
      with:
        ref: ${{ github.event.pull_request.head.sha }}
||||||| Stash base
=======
    # now we need to checkout the feature branch
    # and run the build/test there, but within the context of the ngrok/ngrok-operator repo
    - run: |
        git fetch origin ${{ github.event.pull_request.head.ref }}:${{ github.event.pull_request.head.ref }}
        git checkout ${{ github.event.pull_request.head.ref }}
>>>>>>> Stashed changes
    - uses: "./.github/actions/build-and-test"
      with:
        run-e2e: true
        go-version: ${{ env.GO_VERSION }}
        ngrok-api-key: ${{ secrets.NGROK_CI_API_KEY }}
        ngrok-authtoken: ${{ secrets.NGROK_CI_AUTHTOKEN }}
